\echo Use "CREATE EXTENSION yezzey" to load this file. \quit

CREATE SCHEMA yezzey;

CREATE TABLE yezzey.metatable(relname TEXT NOT NULL UNIQUE) DISTRIBUTED REPLICATED;

CREATE OR REPLACE FUNCTION yezzey.offload_relation(reloid OID) RETURNS void
AS 'MODULE_PATHNAME'
VOLATILE
EXECUTE ON ALL SEGMENTS
LANGUAGE C STRICT;


-- CREATE OR REPLACE FUNCTION yezzey.offload_relation_status(relname TEXT) RETURNS void
-- AS 'MODULE_PATHNAME'
-- VOLATILE
-- LANGUAGE C STRICT;


CREATE OR REPLACE FUNCTION yezzey.force_segment_offload(reloid OID, segid INT) RETURNS void
AS 'MODULE_PATHNAME'
VOLATILE
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION yezzey.lock_aotable_seg(reloid OID, segno INT) RETURNS void
AS 'MODULE_PATHNAME'
VOLATILE
LANGUAGE C STRICT;

