#ifndef YEZZEY_YSTAT_H
#define YEZZEY_YSTAT_H

#define NUM_YEZZEY_OFFLOAD_STATE_COLS 5
#define NUM_USED_OFFLOAD_PER_SEGMENT_STATUS 6
#define NUM_USED_OFFLOAD_PER_SEGMENT_STATUS_STRUCT 7


#endif /* YEZZEY_YSTAT_H */